import sys
import os

target = r'c:\Users\班\Desktop\A3_agent\backend\core\mcp_client.py'

lines = []
lines.append('"""')
lines.append('A3 MCP Client 适配层 — 统一调度 stdio / SSE / HTTP 多通道')
lines.append('')
lines.append('对外单一接口：')
lines.append('    mcp_client.call_tool(name, **kwargs) -> Any')
lines.append('    mcp_client.list_tools() -> list[ToolDefinition]')
lines.append('')
lines.append('支持：')
lines.append('1. 内置本地工具 MCP Server（stdio，自动拉起子进程）')
lines.append('2. 外部 MCP Server（SSE/HTTP，通过 config 注册）')
lines.append('"""')
lines.append('from __future__ import annotations')
lines.append('')
lines.append('import asyncio')
lines.append('import json')
lines.append('import logging')
lines.append('import sys')
lines.append('from pathlib import Path')
lines.append('from typing import Any, Optional')
lines.append('')
lines.append('from core.protocol import ToolDefinition')
lines.append('')
lines.append('logger = logging.getLogger(__name__)')
lines.append('')
lines.append('')
lines.append('class McpToolClient:')
lines.append('    """MCP 多通道工具客户端"""')
lines.append('')
lines.append('    def __init__(self, backend_root: Optional[Path] = None):')
lines.append('        self._backend_root = backend_root or Path(__file__).resolve().parent.parent')
lines.append('        self._python_exe = self._backend_root / ".venv" / "Scripts" / "python.exe"')
lines.append('        self._server_script = self._backend_root / "mcp_server.py"')
lines.append('        # 运行时状态')
lines.append('        self._lock = asyncio.Lock()')
lines.append('        self._stdio_session = None  # ClientSession')
lines.append('        self._stdio_proc_ctx = None  # asyncgenerator context')
lines.append('        self._tool_to_server: dict[str, str] = {}  # tool_name -> server_id')
lines.append('        self._server_sessions: dict[str, Any] = {}  # server_id -> ClientSession')
lines.append('        self._initialized = False')
lines.append('')
lines.append('    # ==================== 初始化 ====================')
lines.append('')
lines.append('    async def ensure_initialized(self):')
lines.append('        """懒加载初始化：启动本地 stdio MCP Server + 加载外部 MCP 配置"""')
lines.append('        if self._initialized:')
lines.append('            return')
lines.append('        async with self._lock:')
lines.append('            if self._initialized:')
lines.append('                return')
lines.append('            # 1. 启动本地 stdio MCP Server')
lines.append('            await self._start_local_stdio()')
lines.append('            # 2. 注册外部 MCP Servers')
lines.append('            await self._load_external_servers()')
lines.append('            self._initialized = True')
lines.append('            logger.info(f"MCP Client 初始化完成，已发现工具: {list(self._tool_to_server.keys())}")')
lines.append('')
lines.append('    async def _start_local_stdio(self):')
lines.append('        """拉起本地工具 MCP Server 子进程并建立会话"""')
lines.append('        try:')
lines.append('            from mcp.client.stdio import stdio_client, StdioServerParameters')
lines.append('            from mcp import ClientSession')
lines.append('')
lines.append('            params = StdioServerParameters(')
lines.append('                command=str(self._python_exe),')
lines.append('                args=[str(self._server_script)],')
lines.append('                cwd=str(self._backend_root),')
lines.append('            )')
lines.append('            ctx = stdio_client(params)')
lines.append('            read, write = await ctx.__anext__()')
lines.append('            self._stdio_proc_ctx = ctx')
lines.append('            session = ClientSession(read, write)')
lines.append('            await session.initialize()')
lines.append('            await self._index_session_tools("local", session)')
lines.append('            self._stdio_session = session')
lines.append('            self._server_sessions["local"] = session')
lines.append('            logger.info(f"本地 stdio MCP Server 会话已建立，工具数: {len([k for k,v in self._tool_to_server.items() if v==\'local\'])}")')
lines.append('        except Exception as e:')
lines.append('            logger.exception(f"启动本地 stdio MCP Server 失败: {e}")')
lines.append('            raise')
lines.append('')
lines.append('    async def _load_external_servers(self):')
lines.append('        """从 core/mcp_config.py 读取外部 MCP Server 配置并建立会话"""')
lines.append('        try:')
lines.append('            from core.mcp_config import EXTERNAL_MCP_SERVERS')
lines.append('        except ImportError:')
lines.append('            EXTERNAL_MCP_SERVERS = {}')
lines.append('        for sid, cfg in EXTERNAL_MCP_SERVERS.items():')
lines.append('            try:')
lines.append('                session = await self._connect_external(sid, cfg)')
lines.append('                if session is not None:')
lines.append('                    await self._index_session_tools(sid, session)')
lines.append('                    self._server_sessions[sid] = session')
lines.append('                    logger.info(f"外部 MCP Server [{sid}] 连接成功")')
lines.append('            except Exception as e:')
lines.append('                logger.warning(f"外部 MCP Server [{sid}] 连接跳过: {e}")')
lines.append('')
lines.append('    async def _connect_external(self, sid: str, cfg: dict):')
lines.append('        """连接外部 MCP Server（支持 sse / streamable_http）"""')
lines.append('        transport = cfg.get("transport", "sse").lower()')
lines.append('        url = cfg.get("url")')
lines.append('        if not url:')
lines.append('            return None')
lines.append('        from mcp import ClientSession')
lines.append('        if transport == "sse":')
lines.append('            from mcp.client.sse import sse_client')
lines.append('            read, write = await sse_client(url).__anext__()')
lines.append('        elif transport in ("http", "streamable_http"):')
lines.append('            from mcp.client.streamable_http import streamable_http_client')
lines.append('            read, write = await streamable_http_client(url).__anext__()')
lines.append('        else:')
lines.append('            raise ValueError(f"未知 transport: {transport}")')
lines.append('        session = ClientSession(read, write)')
lines.append('        await session.initialize()')
lines.append('        return session')
lines.append('')
lines.append('    async def _index_session_tools(self, server_id: str, session):')
lines.append('        """从会话列出工具并建立 tool_name -> server_id 索引"""')
lines.append('        from mcp.types import ListToolsResult')
lines.append('        result = await session.list_tools()')
lines.append('        tools = getattr(result, "tools", []) or []')
lines.append('        for t in tools:')
lines.append('            name = getattr(t, "name", None)')
lines.append('            if name:')
lines.append('                self._tool_to_server[name] = server_id')
lines.append('')
lines.append('    # ==================== 对外 API ====================')
lines.append('')
lines.append('    async def list_tools(self) -> list[ToolDefinition]:')
lines.append('        """列出所有可用工具（本地+外部）"""')
lines.append('        await self.ensure_initialized()')
lines.append('        result: list[ToolDefinition] = []')
lines.append('        seen: set[str] = set()')
lines.append('        for sid, session in self._server_sessions.items():')
lines.append('            try:')
lines.append('                lr = await session.list_tools()')
lines.append('                for t in getattr(lr, "tools", []) or []:')
lines.append('                    name = getattr(t, "name", "")')
lines.append('                    if not name or name in seen:')
lines.append('                        continue')
lines.append('                    seen.add(name)')
lines.append('                    schema = getattr(t, "inputSchema", None) or {}')
lines.append('                    result.append(ToolDefinition(')
lines.append('                        name=name,')
lines.append('                        description=getattr(t, "description", "") or "",')
lines.append('                        parameters=schema,')
lines.append('                    ))')
lines.append('            except Exception as e:')
lines.append('                logger.warning(f"[{sid}] list_tools 失败: {e}")')
lines.append('        return result')
lines.append('')
lines.append('    async def call_tool(self, name: str, **kwargs) -> Any:')
lines.append('        """调用工具，自动路由到对应的 MCP Server"""')
lines.append('        await self.ensure_initialized()')
lines.append('        server_id = self._tool_to_server.get(name)')
lines.append('        if server_id is None:')
lines.append('            # 尝试重新索引一次（可能是新注册的外部 Server）')
lines.append('            await self._reload_all_tools()')
lines.append('            server_id = self._tool_to_server.get(name)')
lines.append('            if server_id is None:')
lines.append('                raise KeyError(f"[MCP] 未找到工具: {name}. 可用: {sorted(self._tool_to_server.keys())}")')
lines.append('        session = self._server_sessions.get(server_id)')
lines.append('        if session is None:')
lines.append('            raise RuntimeError(f"[MCP] Server [{server_id}] 无可用会话")')
lines.append('        raw = await session.call_tool(name, arguments=kwargs)')
lines.append('        return self._parse_result(raw, name)')
lines.append('')
lines.append('    async def _reload_all_tools(self):')
lines.append('        self._tool_to_server.clear()')
lines.append('        for sid, session in self._server_sessions.items():')
lines.append('            await self._index_session_tools(sid, session)')
lines.append('')
lines.append('    @staticmethod')
lines.append('    def _parse_result(raw: Any, tool_name: str) -> Any:')
lines.append('        """将 MCP CallToolResult（TextContent[] / JSON）解析为 Python 对象"""')
lines.append('        try:')
lines.append('            content = getattr(raw, "content", None) or []')
lines.append('            if not content:')
lines.append('                return None')
lines.append('            # 拼接所有 text 片段')
lines.append('            texts: list[str] = []')
lines.append('            for c in content:')
lines.append('                ctype = getattr(c, "type", "")')
lines.append('                is_err = getattr(c, "isError", False)')
lines.append('                if ctype == "text":')
lines.append('                    t = getattr(c, "text", "")')
lines.append('                    if is_err:')
lines.append('                        logger.warning(f"[MCP][{tool_name}] 返回错误: {t[:200]}")')
lines.append('                    texts.append(t)')
lines.append('            combined = "\\n".join(texts).strip()')
lines.append('            if not combined:')
lines.append('                return None')
lines.append('            # 尝试 JSON 解析')
lines.append('            try:')
lines.append('                return json.loads(combined)')
lines.append('            except (json.JSONDecodeError, ValueError):')
lines.append('                return combined')
lines.append('        except Exception as e:')
lines.append('            logger.exception(f"[MCP][{tool_name}] 解析结果失败: {e}")')
lines.append('            return raw')
lines.append('')
lines.append('    # ==================== 生命周期 ====================')
lines.append('')
lines.append('    async def close(self):')
lines.append('        """关闭所有会话和子进程"""')
lines.append('        for sid, session in list(self._server_sessions.items()):')
lines.append('            try:')
lines.append('                await session.close()')
lines.append('            except Exception:')
lines.append('                pass')
lines.append('        self._server_sessions.clear()')
lines.append('        self._tool_to_server.clear()')
lines.append('        self._stdio_session = None')
lines.append('        if self._stdio_proc_ctx is not None:')
lines.append('            try:')
lines.append('                await self._stdio_proc_ctx.aclose()')
lines.append('            except Exception:')
lines.append('                pass')
lines.append('            self._stdio_proc_ctx = None')
lines.append('        self._initialized = False')
lines.append('        logger.info("MCP Client 已关闭")')
lines.append('')
lines.append('')
lines.append('# 全局单例')
lines.append('_mcp_client_instance: Optional[McpToolClient] = None')
lines.append('')
lines.append('')
lines.append('def get_mcp_client() -> McpToolClient:')
lines.append('    global _mcp_client_instance')
lines.append('    if _mcp_client_instance is None:')
lines.append('        _mcp_client_instance = McpToolClient()')
lines.append('    return _mcp_client_instance')
lines.append('')
lines.append('')
lines.append('__all__ = ["McpToolClient", "get_mcp_client"]')
lines.append('')

with open(target, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f'Written {len(lines)} lines to {target}')
print(f'File size: {os.path.getsize(target)} bytes')
